import { Meeting, Schedule } from "@prisma/client"

const meetings = [
  {
    Day: "Saturday",
    City: "Jackson",
    Name: "10 & 6 Group",
    Time: 1000,
    Place: "1st United Methodist Church",
    Address: "200 South Chruch Street",
    Additional_Info: "O/S",
  },
  {
    Day: "Saturday",
    City: "Jackson",
    Name: "Rebos Noon",
    Time: 1200,
    Place: "Rebos Clubhouse",
    Address: "219 North Parkway Suite 6",
    Additional_Info: "O/D",
  },
  {
    Day: "Saturday",
    City: "Paris",
    Name: "Serenity Group",
    Time: 1200,
    Place: "Serenity House",
    Address: "302 South Poplar Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Saturday",
    City: "Paris",
    Name: "Fellowship Group",
    Time: 1600,
    Place: "---",
    Address: "3530 US-79",
    Additional_Info: "O/D",
  },
  {
    Day: "Saturday",
    City: "Jackson",
    Name: "Friendship Group",
    Time: 1700,
    Place: "Lambuth Memorial",
    Address: "160 Campbell Street",
    Additional_Info: "BB",
  },
  {
    Day: "Saturday",
    City: "Jackson",
    Name: "Came to Believe",
    Time: 1800,
    Place: "Rebos Clubhouse",
    Address: "219 North Parkway Suite 6",
    Additional_Info: "O/D",
  },
  {
    Day: "Saturday",
    City: "Parsons",
    Name: "Serenity Group",
    Time: 1830,
    Place: "Methodist Church",
    Address: "49 3rd Street East",
    Additional_Info: "O/D",
  },
  {
    Day: "Saturday",
    City: "Dyersburg",
    Name: "New Attitude Group",
    Time: 1900,
    Place: "---",
    Address: "900 East Court Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Saturday",
    City: "Martin",
    Name: "Martin Group",
    Time: 1900,
    Place: "---",
    Address: "114 Church Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Saturday",
    City: "Paris",
    Name: "Serenity Group",
    Time: 1900,
    Place: "Serenity House",
    Address: "302 South Poplar Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Saturday",
    City: "Selmer",
    Name: "Selmer Group",
    Time: 1900,
    Place: "---",
    Address: "456 Industrial Park Drive",
    Additional_Info: "C/D",
  },
  {
    Day: "Saturday",
    City: "Jackson",
    Name: "Unity Group",
    Time: 1930,
    Place: "Rebos Clubhouse",
    Address: "219 North Parkway Suite 6",
    Additional_Info: "O/S",
  },
  {
    Day: "Saturday",
    City: "Adamsville",
    Name: "Pioneer Group",
    Time: 2000,
    Place: "1st Christian Church",
    Address: "254 North Maple",
    Additional_Info: "O/D",
  },
  {
    Day: "Saturday",
    City: "Milan",
    Name: "Fellowship Group",
    Time: 2000,
    Place: "---",
    Address: "1099 East Van Hook",
    Additional_Info: "O/D",
  },
  {
    Day: "Saturday",
    City: "Ripley",
    Name: "Ripley Group",
    Time: 2000,
    Place: "Ave Maria Catholic Church",
    Address: "664 Washington Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Sunday",
    City: "Jackson",
    Name: "Unity Group",
    Time: 800,
    Place: "Rebos Clubhouse",
    Address: "219 North Parkway Suite 6",
    Additional_Info: "C/D",
  },
  {
    Day: "Sunday",
    City: "Jackson",
    Name: "10 & 6 Group",
    Time: 1000,
    Place: "1st United Methodist Church",
    Address: "200 South Church Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Sunday",
    City: "Martin",
    Name: "Martin Group",
    Time: 1000,
    Place: "---",
    Address: "114 Church Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Sunday",
    City: "Paris",
    Name: "Serenity Group",
    Time: 1200,
    Place: "Serenity House",
    Address: "302 South Poplar Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Sunday",
    City: "Ripley",
    Name: "New Life",
    Time: 1500,
    Place: "---",
    Address: "144 Halliburton Street",
    Additional_Info: "---",
  },
  {
    Day: "Sunday",
    City: "Jackson",
    Name: "Youngtimers Group",
    Time: 1500,
    Place: "Lambuth Memorial",
    Address: "160 Campbell Street",
    Additional_Info: "BB",
  },
  {
    Day: "Sunday",
    City: "Paris",
    Name: "Fellowship Group",
    Time: 1730,
    Place: "---",
    Address: "3530 US-79",
    Additional_Info: "O/D",
  },
  {
    Day: "Sunday",
    City: "Jackson",
    Name: "Came to Believe",
    Time: 1800,
    Place: "Rebos Clubhouse",
    Address: "219 North Parkway Suite 6",
    Additional_Info: "O/D",
  },
  {
    Day: "Sunday",
    City: "Savannah",
    Name: "Savannah Group",
    Time: 1800,
    Place: "Grace Point Chruch",
    Address: "269 Wayne Road",
    Additional_Info: "O/Newcomers",
  },
  {
    Day: "Sunday",
    City: "Henderson",
    Name: "Keep It Simple Group",
    Time: 1900,
    Place: "United Methodist Church",
    Address: "131 North Avenue",
    Additional_Info: "O/D",
  },
  {
    Day: "Sunday",
    City: "Jackson",
    Name: "Tucker Street Group",
    Time: 1900,
    Place: "1st United Methodist Church",
    Address: "200 South Church Street",
    Additional_Info: "O/D, Last - O/S",
  },
  {
    Day: "Sunday",
    City: "Lexington",
    Name: "Winners Group",
    Time: 1900,
    Place: "---",
    Address: "125 Montgomery Way",
    Additional_Info: "O/D, Last - O/S",
  },
  {
    Day: "Sunday",
    City: "Macon",
    Name: "Macon AA Meeting",
    Time: 1900,
    Place: "Macon United Methodist Church",
    Address: "8740 Macon Road",
    Additional_Info: "C/D",
  },
  {
    Day: "Sunday",
    City: "McKenzie",
    Name: "McKenzie Group",
    Time: 1900,
    Place: "---",
    Address: "14800 Highland Drive",
    Additional_Info: "O/D, Last - C/L",
  },
  {
    Day: "Sunday",
    City: "Bells",
    Name: "Bells Group",
    Time: 1900,
    Place: "---",
    Address: "101 West Front Street",
    Additional_Info: "O/D, Last - SS",
  },
  {
    Day: "Sunday",
    City: "Newbern",
    Name: "Newbern Group",
    Time: 2000,
    Place: "Cumberland Presbyterian Church",
    Address: "310 East Main",
    Additional_Info: "O/D",
  },
  {
    Day: "Monday",
    City: "Jackson",
    Name: "10 & 6 Group",
    Time: 1000,
    Place: "1st United Methodist Church",
    Address: "200 South Church Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Monday",
    City: "Adamsville",
    Name: "Pioneer Group",
    Time: 1100,
    Place: "1st Christian Church",
    Address: "254 North Maple",
    Additional_Info: "O/D",
  },
  {
    Day: "Monday",
    City: "Jackson",
    Name: "Hope Noon Group",
    Time: 1200,
    Place: "1st United Methodist Church",
    Address: "200 South Chruch Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Monday",
    City: "Jackson",
    Name: "Rebos Noon",
    Time: 1200,
    Place: "Rebos Clubhouse",
    Address: "219 North Parkway Suite 6",
    Additional_Info: "O/D",
  },
  {
    Day: "Monday",
    City: "Martin",
    Name: "Martin Group",
    Time: 1200,
    Place: "---",
    Address: "114 Church Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Monday",
    City: "Paris",
    Name: "Serenity Group",
    Time: 1200,
    Place: "Serenity House",
    Address: "302 South Poplar Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Monday",
    City: "Jackson",
    Name: "P.U.S.H.",
    Time: 1400,
    Place: "Downtown Jackson Library (Big Room)",
    Address: "433 East Lafayette Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Monday",
    City: "Jackson",
    Name: "Came to Believe",
    Time: 1800,
    Place: "Rebos Clubhouse",
    Address: "219 North Parkway Suite 6",
    Additional_Info: "O/D",
  },
  {
    Day: "Monday",
    City: "Paris",
    Name: "Fellowship Group",
    Time: 1830,
    Place: "---",
    Address: "3530 US-79",
    Additional_Info: "O/D",
  },
  {
    Day: "Monday",
    City: "Covington",
    Name: "Overcomers Group",
    Time: 1900,
    Place: "St. Mathews Episcopal Church (Parish Hall)",
    Address: "303 Munford Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Monday",
    City: "Dover",
    Name: "Dover Group",
    Time: 1900,
    Place: "Legacy Baptist Church",
    Address: "Hwy. 79 North",
    Additional_Info: "O/D",
  },
  {
    Day: "Monday",
    City: "Medina",
    Name: "Medina Group",
    Time: 1900,
    Place: "---",
    Address: "500 West Church Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Monday",
    City: "Tiptonville",
    Name: "Tiptonville Group",
    Time: 1900,
    Place: "Court House",
    Address: "229 Church Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Monday",
    City: "Savannah",
    Name: "Savannah Group",
    Time: 1900,
    Place: "Grace Point Chruch",
    Address: "269 Wayne Road",
    Additional_Info: "C/D",
  },
  {
    Day: "Monday",
    City: "Dyersburg",
    Name: "New Attitude Group",
    Time: 1900,
    Place: "---",
    Address: "900 East Court Street",
    Additional_Info: "BB",
  },
  {
    Day: "Monday",
    City: "Somerville",
    Name: "Triangle Group",
    Time: 1900,
    Place: "Somerville Methodist Church",
    Address: "202 South East Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Monday",
    City: "Bolivar",
    Name: "Bolivar Group",
    Time: 1900,
    Place: "1st United Methodist Church",
    Address: "218 West Market Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Monday",
    City: "Lexington",
    Name: "Winners Group",
    Time: 2000,
    Place: "---",
    Address: "125 Montgomery Way",
    Additional_Info: "BB",
  },
  {
    Day: "Monday",
    City: "Huntingdon",
    Name: "Huntingdon Group",
    Time: 2000,
    Place: "Holy Family Catholic Church",
    Address: "265 Cotham Drive",
    Additional_Info: "C/D",
  },
  {
    Day: "Monday",
    City: "Jackson",
    Name: "Friendship Group",
    Time: 2000,
    Place: "Lambuth Memorial",
    Address: "160 Campbell Street",
    Additional_Info: "O/S",
  },
  {
    Day: "Monday",
    City: "Brownsville",
    Name: "Brownsville Group",
    Time: 2000,
    Place: "W.O.W. Building",
    Address: "1341 East Main Street",
    Additional_Info: "O/D, 1st Monday - BB",
  },
  {
    Day: "Tuesday",
    City: "Jackson",
    Name: "10 & 6 Group",
    Time: 1000,
    Place: "1st United Methodist Church",
    Address: "200 South Church Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Tuesday",
    City: "Jackson",
    Name: "Rebos Noon",
    Time: 1200,
    Place: "Rebos Clubhouse",
    Address: "219 North Parkway Suite 6",
    Additional_Info: "O/D",
  },
  {
    Day: "Tuesday",
    City: "Paris",
    Name: "Serenity Group",
    Time: 1200,
    Place: "Serenity House",
    Address: "302 South Poplar Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Tuesday",
    City: "Martin",
    Name: "Martin Group",
    Time: 1200,
    Place: "---",
    Address: "114 Church Street",
    Additional_Info: "O/BB",
  },
  {
    Day: "Tuesday",
    City: "Paris",
    Name: "Fellowship Group",
    Time: 1800,
    Place: "---",
    Address: "3530 US-79",
    Additional_Info: "Grapevine/ 12 & 12 Book Study",
  },
  {
    Day: "Tuesday",
    City: "Jackson",
    Name: "Came to Believe",
    Time: 1800,
    Place: "Rebos Clubhouse",
    Address: "219 North Parkway Suite 6",
    Additional_Info: "O/D",
  },
  {
    Day: "Tuesday",
    City: "Adamsville",
    Name: "Pioneer Group",
    Time: 1830,
    Place: "1st Christian Church",
    Address: "254 North Maple",
    Additional_Info: "O/BB",
  },
  {
    Day: "Tuesday",
    City: "Paris",
    Name: "Serenity Group",
    Time: 1830,
    Place: "Serenity House",
    Address: "302 South Poplar Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Tuesday",
    City: "Alamo",
    Name: "Alamo Group",
    Time: 1900,
    Place: "1st United Methodist Church",
    Address: "---",
    Additional_Info: "O/D, First - O/S",
  },
  {
    Day: "Tuesday",
    City: "Buchanan",
    Name: "Lake Area Group",
    Time: 1900,
    Place: "United Methodist Church",
    Address: "3116 West Antioch Road",
    Additional_Info: "C/D",
  },
  {
    Day: "Tuesday",
    City: "Camden",
    Name: "Camden Group",
    Time: 1900,
    Place: "St. Mary's Catholic Church",
    Address: "220 West Main Street",
    Additional_Info: "O/S",
  },
  {
    Day: "Tuesday",
    City: "Henderson",
    Name: "Keep It Simple Group",
    Time: 1900,
    Place: "1st United Methodist Church",
    Address: "131 North Avenue",
    Additional_Info: "O/D",
  },
  {
    Day: "Tuesday",
    City: "Oakland",
    Name: "Big Book Study",
    Time: 1900,
    Place: "---",
    Address: "8695 Hwy 64",
    Additional_Info: "BB",
  },
  {
    Day: "Tuesday",
    City: "Jackson",
    Name: "12 & 12 Group",
    Time: 1900,
    Place: "Skyline Church of Christ",
    Address: "1024 Skyline",
    Additional_Info: "C/D, First - SS NSS",
  },
  {
    Day: "Tuesday",
    City: "Union City",
    Name: "Never Alone Group",
    Time: 1900,
    Place: "St. James Episcopal Church",
    Address: "422 East Church Street",
    Additional_Info: "BB - O/D",
  },
  {
    Day: "Tuesday",
    City: "Humboldt",
    Name: "Bills Corner",
    Time: 1900,
    Place: "Christ Ministries Church",
    Address: "286 Hwy 45 West",
    Additional_Info: "---",
  },
  {
    Day: "Tuesday",
    City: "Covington",
    Name: "Overcomers Group",
    Time: 1900,
    Place: "St. Mathews Episcopal Church (Parish Hall)",
    Address: "303 Munford Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Tuesday",
    City: "Martin",
    Name: "Martin Group",
    Time: 2000,
    Place: "---",
    Address: "114 Church Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Tuesday",
    City: "Somerville",
    Name: "Triangle Group",
    Time: 2000,
    Place: "---",
    Address: "212 West Market Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Tuesday",
    City: "Trenton",
    Name: "Triangle Group",
    Time: 2000,
    Place: "Beside First Presbyterian Church",
    Address: "503 South High Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Tuesday",
    City: "Adamsville",
    Name: "Pioneer Group",
    Time: 2000,
    Place: "1st Christian Church",
    Address: "254 North Maple",
    Additional_Info: "O/D",
  },
  {
    Day: "Tuesday",
    City: "Jackson",
    Name: "Serenity Group",
    Time: 2000,
    Place: "Aldersgate Methodist Church",
    Address: "1050 North Parkway",
    Additional_Info: "C/D",
  },
  {
    Day: "Wednesday",
    City: "Jackson",
    Name: "10 & 6 Group",
    Time: 1000,
    Place: "1st United Methodist Church",
    Address: "200 South Church Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Wednesday",
    City: "Jackson",
    Name: "---",
    Time: 1200,
    Place: "1st United Methodist Church",
    Address: "200 South Church Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Wednesday",
    City: "Jackson",
    Name: "Rebos Noon",
    Time: 1200,
    Place: "Rebos Clubhouse",
    Address: "219 North Parkway Suite 6",
    Additional_Info: "C/D",
  },
  {
    Day: "Wednesday",
    City: "Martin",
    Name: "Martin Group",
    Time: 1200,
    Place: "---",
    Address: "114 Church Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Wednesday",
    City: "Paris",
    Name: "Serenity Group",
    Time: 1200,
    Place: "Serenity House",
    Address: "302 South Poplar Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Wednesday",
    City: "Jackson",
    Name: "Hope Noon Group",
    Time: 1200,
    Place: "United Methodist Church",
    Address: "200 South Church Street",
    Additional_Info: "Last - O/S",
  },
  {
    Day: "Wednesday",
    City: "Jackson",
    Name: "P.U.S.H.",
    Time: 1400,
    Place: "Downtown Jackson Library (Big Room)",
    Address: "433 East Lafayette Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Wednesday",
    City: "Jackson",
    Name: "Came to Believe",
    Time: 1800,
    Place: "Rebos Clubhouse",
    Address: "219 North Parkway Suite 6",
    Additional_Info: "BB",
  },
  {
    Day: "Wednesday",
    City: "Martin",
    Name: "Martin Group",
    Time: 1830,
    Place: "---",
    Address: "114 Church Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Wednesday",
    City: "Paris",
    Name: "Fellowship Group",
    Time: 1830,
    Place: "---",
    Address: "3530 US-79",
    Additional_Info: "C/BB",
  },
  {
    Day: "Wednesday",
    City: "Jackson",
    Name: "Tucker Street Group",
    Time: 1900,
    Place: "1st United Methodist Church",
    Address: "200 South Church Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Wednesday",
    City: "Tiptonville",
    Name: "Tiptonville Group",
    Time: 1900,
    Place: "Court House",
    Address: "229 Church Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Wednesday",
    City: "McKenzie",
    Name: "McKenzie Group",
    Time: 1900,
    Place: "---",
    Address: "14800 Highland Drive",
    Additional_Info: "BB",
  },
  {
    Day: "Wednesday",
    City: "Brownsville",
    Name: "Brownsville Group",
    Time: 2000,
    Place: "W.O.W. Building",
    Address: "1341 East Main Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Wednesday",
    City: "Savannah",
    Name: "Savannah Group",
    Time: 2000,
    Place: "Grace Point Chruch",
    Address: "269 Wayne Road",
    Additional_Info: "O/D",
  },
  {
    Day: "Wednesday",
    City: "Lexington",
    Name: "Winners Group",
    Time: 2000,
    Place: "---",
    Address: "125 Montgomery Way",
    Additional_Info: "C/D",
  },
  {
    Day: "Wednesday",
    City: "Ripley",
    Name: "Ripley Group",
    Time: 2000,
    Place: "Ave Maria Catholic Church",
    Address: "664 Washington Street",
    Additional_Info: "---",
  },
  {
    Day: "Thursday",
    City: "Jackson",
    Name: "10 & 6 Group",
    Time: 1000,
    Place: "1st United Methodist Church",
    Address: "200 South Church Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Thursday",
    City: "Covington",
    Name: "Overcomers Group",
    Time: 1200,
    Place: "St. Mathews Episcopal Church (Parish Hall)",
    Address: "303 Munford Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Thursday",
    City: "Jackson",
    Name: "Rebos Noon",
    Time: 1200,
    Place: "Rebos Clubhouse",
    Address: "219 North Parkway Suite 6",
    Additional_Info: "O/D",
  },
  {
    Day: "Thursday",
    City: "Paris",
    Name: "Serenity Group",
    Time: 1200,
    Place: "Serenity House",
    Address: "302 South Poplar Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Thursday",
    City: "Jackson",
    Name: "Came to Believe",
    Time: 1800,
    Place: "Rebos Clubhouse",
    Address: "219 North Parkway Suite 6",
    Additional_Info: "O/D",
  },
  {
    Day: "Thursday",
    City: "Paris",
    Name: "Fellowship Group",
    Time: 1830,
    Place: "---",
    Address: "3530 US-79",
    Additional_Info: "Men's Meeting",
  },
  {
    Day: "Thursday",
    City: "Parsons",
    Name: "Serenity Group",
    Time: 1830,
    Place: "Methodist Church",
    Address: "49 3rd Street East",
    Additional_Info: "C/D",
  },
  {
    Day: "Thursday",
    City: "Henderson",
    Name: "Keep It Simple Group",
    Time: 1900,
    Place: "1st United Methodist Church",
    Address: "131 North Avenue",
    Additional_Info: "O/D",
  },
  {
    Day: "Thursday",
    City: "Milan",
    Name: "Fellowship Group",
    Time: 1900,
    Place: "---",
    Address: "1099 East Van Hook",
    Additional_Info: "O/D - NSS",
  },
  {
    Day: "Thursday",
    City: "Humboldt",
    Name: "Bills Corner",
    Time: 1900,
    Place: "Christ Ministries Church",
    Address: "286 Hwy 45 West",
    Additional_Info: "---",
  },
  {
    Day: "Thursday",
    City: "Jackson",
    Name: "12 & 12 Group",
    Time: 1900,
    Place: "Skyline Church of Christ",
    Address: "1024 Skyline",
    Additional_Info: "O/D, Last - O/D NSS",
  },
  {
    Day: "Thursday",
    City: "Jackson",
    Name: "Promise Group",
    Time: 1900,
    Place: "All Saints Anglican Church",
    Address: "212 McClellan Road",
    Additional_Info: "C/D",
  },
  {
    Day: "Thursday",
    City: "Tiptonville",
    Name: "Tiptonville Group",
    Time: 1900,
    Place: "Court House",
    Address: "229 Church Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Thursday",
    City: "Dyersburg",
    Name: "New Attitude Group",
    Time: 1900,
    Place: "---",
    Address: "900 East Court Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Thursday",
    City: "Somerville",
    Name: "Triangle Group",
    Time: 1900,
    Place: "Somerville Methodist Church",
    Address: "202 South East Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Thursday",
    City: "Bells",
    Name: "Bells Group",
    Time: 1900,
    Place: "---",
    Address: "101 West Front Street",
    Additional_Info: "O/D, Last - BB",
  },
  {
    Day: "Thursday",
    City: "Adamsville",
    Name: "Pioneer Group",
    Time: 2000,
    Place: "1st Christian Church",
    Address: "254 North Maple",
    Additional_Info: "C/D",
  },
  {
    Day: "Thursday",
    City: "Jackson",
    Name: "Friendship Group",
    Time: 2000,
    Place: "Lambuth Memorial",
    Address: "160 Campbell Street",
    Additional_Info: "Candlelight, C/D",
  },
  {
    Day: "Thursday",
    City: "Martin",
    Name: "Martin Group",
    Time: 2000,
    Place: "---",
    Address: "114 Church Street",
    Additional_Info: "O/Literature",
  },
  {
    Day: "Thursday",
    City: "Somerville",
    Name: "---",
    Time: 2000,
    Place: "---",
    Address: "212 West Market Street (Across from Library)",
    Additional_Info: "O/D, Last - O/S",
  },
  {
    Day: "Thursday",
    City: "Trenton",
    Name: "Triangle Group",
    Time: 2000,
    Place: "Beside First Presbyterian Church",
    Address: "503 South High Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Friday",
    City: "Jackson",
    Name: "10 & 6 Group",
    Time: 1000,
    Place: "1st United Methodist Church",
    Address: "200 South Church Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Friday",
    City: "Jackson",
    Name: "Hope Noon Group",
    Time: 1200,
    Place: "1st United Methodist Church",
    Address: "200 South Church Street",
    Additional_Info: "Last - O/S",
  },
  {
    Day: "Friday",
    City: "Jackson",
    Name: "Rebos Noon",
    Time: 1200,
    Place: "Rebos Clubhouse",
    Address: "219 North Parkway Suite 6",
    Additional_Info: "C/D",
  },
  {
    Day: "Friday",
    City: "Martin",
    Name: "Martin Group",
    Time: 1200,
    Place: "---",
    Address: "114 Church Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Friday",
    City: "Paris",
    Name: "Serenity Group",
    Time: 1200,
    Place: "Serenity House",
    Address: "302 South Poplar Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Friday",
    City: "Jackson",
    Name: "P.U.S.H.",
    Time: 1400,
    Place: "Downtown Jackson Library (Big Room)",
    Address: "433 East Lafayette Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Friday",
    City: "Jackson",
    Name: "Came to Believe",
    Time: 1800,
    Place: "Rebos Clubhouse",
    Address: "219 North Parkway Suite 6",
    Additional_Info: "O/D",
  },
  {
    Day: "Friday",
    City: "Paris",
    Name: "Fellowship Group",
    Time: 1830,
    Place: "---",
    Address: "3530 US-79",
    Additional_Info: "O/S",
  },
  {
    Day: "Friday",
    City: "Alamo",
    Name: "Alamo Group",
    Time: 1900,
    Place: "1st United Methodist Church",
    Address: "---",
    Additional_Info: "O/D",
  },
  {
    Day: "Friday",
    City: "Medina",
    Name: "Medina Group",
    Time: 1900,
    Place: "---",
    Address: "500 West Church Street",
    Additional_Info: "C/D",
  },
  {
    Day: "Friday",
    City: "Bolivar",
    Name: "Bolivar Group",
    Time: 1900,
    Place: "1st United Methodist Church",
    Address: "218 West Market Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Friday",
    City: "Camden",
    Name: "Camden Group",
    Time: 1930,
    Place: "St. Mary's Catholic Church",
    Address: "220 West Main Street",
    Additional_Info: "O/D",
  },
  {
    Day: "Friday",
    City: "Jackson",
    Name: "Serenity Group",
    Time: 1000,
    Place: "Aldersgate Methodist Church",
    Address: "150 North Parkway",
    Additional_Info: "O/D, Last O/S",
  },
  {
    Day: "Friday",
    City: "Lexington",
    Name: "Winners Group",
    Time: 1000,
    Place: "---",
    Address: "125 Montgomery Way",
    Additional_Info: "O/D",
  },
  {
    Day: "Friday",
    City: "Savannah",
    Name: "Savannah Group",
    Time: 1000,
    Place: "Grace Point Chruch",
    Address: "269 Wayne Road",
    Additional_Info: "O/S",
  },
  {
    Day: "Friday",
    City: "Huntingdon",
    Name: "Huntingdon Group",
    Time: 1000,
    Place: "Holy Family Catholic Church",
    Address: "265 Cotham Drive",
    Additional_Info: "O/D",
  },
  {
    Day: "Friday",
    City: "Jackson",
    Name: "Youngtimers Group",
    Time: 1100,
    Place: "Lambuth Memorial",
    Address: "160 Campbell Street",
    Additional_Info: "---",
  },
]

// loop through meetings
// only keep unique meetings by name
// add to new meetings array

type MeetingWithSchedules = Partial<Meeting> & { schedules: Partial<Schedule>[] }

let newMeetings: MeetingWithSchedules[] = []

meetings.forEach((meeting) => {
  if (newMeetings.find((newMeeting) => newMeeting.name === meeting.Name) === undefined) {
    const { Name, Address, Additional_Info, City, Place } = meeting
    newMeetings.push({
      name: Name,
      address: Address,
      description: Additional_Info,
      city: City,
      state: "TN",
      placeName: Place,
      schedules: [],
    })
  }
})

// add schedules to meetings
meetings.forEach((meeting) => {
  const { Day, Time, Place, Name } = meeting
  const newMeeting = newMeetings.find((newMeeting) => newMeeting.name === Name)
  if (newMeeting) {
    newMeeting.schedules.push({ dayOfWeek: Day.toUpperCase(), startTime: Time })
  }
})

export default newMeetings
